// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account/addresses" | "/account/orders" | "/account/orders/[orderId]" | "/account/profile" | "/admin" | "/admin/categories" | "/admin/categories/[id]/edit" | "/admin/categories/new" | "/admin/contents" | "/admin/contents/[key]/edit" | "/admin/contents/footer/edit" | "/admin/contents/hero/edit" | "/admin/contents/new" | "/admin/contents/stories/edit" | "/admin/orders" | "/admin/orders/[id]" | "/admin/products" | "/admin/products/[id]" | "/admin/products/[id]/edit" | "/admin/products/new" | "/admin/users" | "/admin/users/[id]" | "/cart" | "/categories" | "/categories/[slug]" | "/checkout" | "/guide" | "/login" | "/order-success/[orderNum]" | "/products" | "/products/[slug]" | "/register" | "/terms" | "/wholesale-guide"
type PageRoutes = never
type LayoutRoutes = "/" | "/account" | "/admin"
type RedirectRoutes = "/wholesale-guide"
type RewriteRoutes = "/api/[[...path]]" | "/uploads/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/account/addresses": {}
  "/account/orders": {}
  "/account/orders/[orderId]": { "orderId": string; }
  "/account/profile": {}
  "/admin": {}
  "/admin/categories": {}
  "/admin/categories/[id]/edit": { "id": string; }
  "/admin/categories/new": {}
  "/admin/contents": {}
  "/admin/contents/[key]/edit": { "key": string; }
  "/admin/contents/footer/edit": {}
  "/admin/contents/hero/edit": {}
  "/admin/contents/new": {}
  "/admin/contents/stories/edit": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/products": {}
  "/admin/products/[id]": { "id": string; }
  "/admin/products/[id]/edit": { "id": string; }
  "/admin/products/new": {}
  "/admin/users": {}
  "/admin/users/[id]": { "id": string; }
  "/api/[[...path]]": { "path"?: string[]; }
  "/cart": {}
  "/categories": {}
  "/categories/[slug]": { "slug": string; }
  "/checkout": {}
  "/guide": {}
  "/login": {}
  "/order-success/[orderNum]": { "orderNum": string; }
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/register": {}
  "/terms": {}
  "/uploads/[[...path]]": { "path"?: string[]; }
  "/wholesale-guide": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/account": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
